# Generated by Django 3.2.4 on 2021-06-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('inStock', models.BooleanField(default=True)),
                ('stocked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-stocked'],
            },
        ),
    ]
